### ISSUE TITLE
Access permissions when importing a new file into the "Assets" project directory

### ISSUE THREAD

**Issue by AdriaPm** [CITM-UPC/VertX-Game-Engine#2]
Hi @pepcots,
we are facing an issue when trying to import a local file from the system to the project's Asset folder. We have the following code, which opens a Window's popup where you can browse and select a file from local to import:

            OPENFILENAME ofn;
		char szFile[260] = { 0 };

		ZeroMemory(&ofn, sizeof(ofn));
		ofn.lStructSize = sizeof(ofn);
		ofn.hwndOwner = NULL;
		ofn.lpstrFile = szFile;
		ofn.lpstrFile[0] = '\0';
		ofn.nMaxFile = sizeof(szFile);
		ofn.lpstrFilter = "All Files (*.*)\0*.*\0";
		ofn.nFilterIndex = 1;
		ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

		if (GetOpenFileName(&ofn) == TRUE) {
			std::filesystem::path selectedFile = szFile;
			std::filesystem::path destinationPath = "Assets/" + selectedFile.filename().string();

			try {
				// Check if the selected file exists
				if (!std::filesystem::exists(selectedFile)) {
					MessageBox(NULL, "Selected file does not exist.", "Error", MB_OK | MB_ICONERROR);
					return;
				}

				// Check if the destination file already exists
				if (std::filesystem::exists(destinationPath)) {
					int result = MessageBox(NULL, "File already exists in 'Assets' directory. Overwrite?", "Warning", MB_YESNO | MB_ICONWARNING);
					if (result == IDNO) {
						return;
					}
				}

				// Copy the file
				std::filesystem::copy_file(selectedFile, destinationPath, std::filesystem::copy_options::overwrite_existing);

				MessageBox(NULL, "File imported to 'Assets' directory.", "Import Successful", MB_OK);
				LOG("EDITOR: File '%s' imported to 'Assets' directory SUCCESSFULLY...", szFile);
			}
			catch (const std::exception& e) {
				MessageBox(NULL, e.what(), "Error due to Access Permissions or other.", MB_OK | MB_ICONERROR);
			}
		}

Whenever you try to import a file from outside the current directory ( '$(ProjectSol)/Editor' ), the program crashes with the following error:
![importingFilesEroor](https://github.com/CITM-UPC/VertX-Game-Engine/assets/99724788/c8a01b6e-5dc7-4cdf-8505-824a1293d12c)
But if you import a file from the current directory, it works, and I think the error goes with the program insufficient permissions from Windows. We try it running it as an Admin and still doesn't work 😞.

I don't know if you can think of any possible solution or anything we can do to import local files from any directory of the pc to the project's Assets folder. Or if there's another easier way...

Thanks anyway.

**Comment by pepcots** [comment]
Hi @AdriaPm !
I'm pretty sure it has nothing to do with the permissions.
It seems to be an unhandled filesystem exception, so, it should be an error in your code.
Maybe it has to do with this:
`"Assets/" + selectedFile.filename().string()`
Take care about operators and operand, in this case, the left operand is a char*.
Try it with:
`string("Assets") + selectedFile.filename().string()`
If you want to create a MessageBox when permissions are failing,m try to catch only the exception that represents that
